<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Slim 3</title>

    <meta title="description" content="An opinionated Slim3 Skeleton">
    <meta title="author" content="Simon Dann <simon.dann@gmail.com>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <style type="text/css">
        body {
            margin: 40px auto;
            max-width: 650px;
            line-height: 1.6;
            font-size: 18px;
            color: #444;
            padding: 0 10px
        }

        h1, h2, h3 {
            line-height: 1.2
        }

        .text-center{
            text-align: center;
        }

    </style>
</head>
<body class="text-center">
<h1>Slim<sup>3</sup> Skeleton</h1>
<div>An opinionated application skeleton for the Slim 3 micro-framework.</div>
</body>
</html>
