<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Slim 3</title>
    <meta title="description" content="An opinionated Slim3 Skeleton">
    <meta title="author" content="Simon Dann <simon.dann@gmail.com>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="assets/css/default.css" rel='stylesheet' type='text/css'>
</head>
<body class="text-center">
<h1>Slim<sup>3</sup> Skeleton</h1>
<div>An opinionated application skeleton for the Slim 3 micro-framework.</div>
</body>
</html>
