<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?=$this->e($title)?> | Slim 3</title>

    <meta title="description" content="An opinionated Slim3 Skeleton">
    <meta title="author" content="Simon Dann <simon.dann@gmail.com>">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="assets/css/default.css" rel='stylesheet' type='text/css'>
</head>
<body>
<?=$this->section('pageBody')?>
</body>
</html>
